id: openstack-network-server-nova
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  fqdn:
    value: null
  management_vip:
    value: null
  neutron_config:
    value: null
  neutron_endpoint:
    value: null
  puppet_modules:
    value: null
  region:
    value: null
  role:
    value: null
  service_endpoint:
    value: null
  use_neutron:
    value: null
