id: api-proxy
handler: puppetv2
version: '8.0'
inputs:
  apache_ports:
    value: null
  fqdn:
    value: null
  master_ip:
    value: null
  max_header_size:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
