language: python
python: 2.7
cache:
    directories:
        - $HOME/.cache/pi
install:
    - pip install coveralls
script:
    - ./run_tests.sh
services:
    - redis-server
after_success:
    cd solar && coveralls
