language: python
python: 2.7
env:
  - PIP_ACCEL_CACHE=$HOME/.pip-accel-cache SOLAR_CONFIG=$TRAVIS_BUILD_DIR/.config SOLAR_SOLAR_DB_HOST=localhost
cache:
    directories:
        - $HOME/.pip-accel-cache
install:
    - pip install pip-accel
    - pip-accel install coveralls
    - pip-accel install -r test-requirements.txt
script:
    - py.test --cov=solar -s solar
services:
    - riak
after_success:
    coveralls
