language: python
python: 2.7
env:
  - PIP_ACCEL_CACHE=$HOME/.pip-accel-cache
cache:
    directories:
        - $HOME/.pip-accel-cache
install:
    - pip install pip-accel
    - pip-accel install coveralls
script:
    - ./run_tests.sh
services:
    - redis-server
after_success:
    cd solar && coveralls
