solar:
  image: solarproject/solar-celery:f2s
  # path inside of the container should be exactly the same as outside
  # because solar uses absolute path to find resoruce actions files
  volumes:
    - /vagrant/.vagrant:/vagrant/.vagrant
    - /vagrant:/solar
    - /vagrant/templates:/vagrant/templates
    - /vagrant/resources:/vagrant/resources
    - /vagrant/library:/vagrant/library
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - RIAK_HOST=riak
    - RIAK_PORT=8087
  # links are not used for configuration because we can rely on non-container
  # based datastores
  links:
    - riak
    - redis

docker run --name solar -d -v /root/solar/solar:/solar -v /root/solar/solard:/solard -v /root/solar/templates:/templates \
-v /root/solar/resources:/resources -v /root/solar/f2s:/f2s \
-v /var/lib/fuel:/var/lib/fuel -v /root/.config/fuel/fuel_client.yaml:/etc/fuel/client/config.yaml -v /etc/puppet/modules:/etc/puppet/modules \
-v /root/.ssh:/root/.ssh \
--link=riak:riak --link=redis:redis solarproject/solar-celery:f2s

riak:
  image: tutum/riak
  ports:
    - 8087:8087
    - 8098:8098
redis:
  image: tutum/redis
  ports:
    - 6379:6379
  environment:
    - REDIS_PASS=**None**
