id: openstack-haproxy-stats
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  service_endpoint:
    value: null
