id: cluster
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  corosync_roles:
    value: null
  fqdn:
    value: null
  network_metadata:
    value: null
  network_scheme:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
