id: cinder-db
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  cinder:
    value: null
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  mysql_custom_setup_class:
    value: null
  mysql_hash:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
