id: murano-db
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  murano:
    value: null
  murano_hash:
    value: null
  mysql_hash:
    value: null
  node_name:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
