id: connectivity_tests
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  repo_setup:
    value: null
  role:
    value: null
