id: ceilometer-radosgw-user
handler: puppetv2
version: '8.0'
inputs:
  ceilometer:
    value: null
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  storage:
    value: null
