id: public_vip_ping
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  fqdn:
    value: null
  network_scheme:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  run_ping_checker:
    value: null
