id: openstack-haproxy-neutron
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  fqdn:
    value: null
  management_vip:
    value: null
  neutron_ipaddresses:
    value: null
  neutron_names:
    value: null
  neutron_nodes:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  use_neutron:
    value: null
