id: sahara-db
handler: puppetv2
version: '8.0'
inputs:
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  mysql_hash:
    value: null
  node_name:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  sahara:
    value: null
  sahara_hash:
    value: null
