handler: puppet
id: 'rabbitmq'
input:
  ip:
    schema: str!
    value:
  # ssh_key:
  #   schema: str!
  #   value:
  # ssh_user:
  #   schema: str!
  #   value:

  port:
    schema: int!
    value: 5672
  management_port:
    schema: int! 
    value: 15672
  git:
    schema: {repository: str!, branch: str!}
    value: {repository: 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git', branch: '5.1.0'}

puppet_module: 'rabbitmq'
tags: []
version: 1.0.0
