id: openstack-network-agents-dhcp
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  debug:
    value: null
  fqdn:
    value: null
  neutron_advanced_configuration:
    value: null
  primary_controller:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  use_neutron:
    value: null
