# data container resource that will fetch data from nailgun
id: role_data
handler: none
version: 0.0.1
managers:
    - managers/from_nailgun.py
    - managers/globals.py
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
  uid:
    type: str!
    value:
  env:
    type: str!
    value:
  tasks:
    value:
  ironic:
    value:
  access:
    value: null
  access_hash:
    value: null
  amqp_hosts:
    value: null
  amqp_port:
    value: null
  apache_ports:
    value: null
  auth_key:
    value: null
  auto_assign_floating_ip:
    value: null
  base_mac:
    value: null
  base_syslog:
    value: null
  base_syslog_hash:
    value: null
  ceilometer:
    value: null
  ceilometer_hash:
    value: null
  ceilometer_nodes:
    value: null
  ceph_monitor_nodes:
    value: null
  ceph_primary_monitor_node:
    value: null
  ceph_rgw_nodes:
    value: null
  cinder:
    value: null
  cinder_hash:
    value: null
  cinder_nodes:
    value: null
  cinder_rate_limits:
    value: null
  cobbler:
    value: null
  corosync:
    value: null
  corosync_roles:
    value: null
  custom_mysql_setup_class:
    value: null
  database_nodes:
    value: null
  database_vip:
    value: null
  debug:
    value: null
  default_gateway:
    value: null
  deployment_id:
    value: null
  deployment_mode:
    value: null
  dns_nameservers:
    value: null
  external_dns:
    value: null
  external_mongo:
    value: null
  external_ntp:
    value: null
  fail_if_error:
    value: null
  fqdn:
    value: null
  fuel_version:
    value: null
  glance:
    value: null
  glance_backend:
    value: null
  glance_hash:
    value: null
  glance_known_stores:
    value: null
  heat:
    value: null
  heat_hash:
    value: null
  heat_roles:
    value: null
  horizon_nodes:
    value: null
  idle_timeout:
    value: null
  ironic_api_nodes:
    value: null
  is_primary_swift_proxy:
    value: null
  kernel_params:
    value: null
  keystone:
    value: null
  keystone_hash:
    value: null
  last_controller:
    value: null
  libvirt_type:
    value: null
  manage_volumes:
    value: null
  management_network_range:
    value: null
  management_vip:
    value: null
  management_vrouter_vip:
    value: null
  master_ip:
    value: null
  max_overflow:
    value: null
  max_pool_size:
    value: null
  max_retries:
    value: null
  memcache_roles:
    value: null
  metadata:
    value: null
  mirror_type:
    value: null
  mongo:
    value: null
  mongo_roles:
    value: null
  mountpoints:
    value: null
  mp:
    value: null
  multi_host:
    value: null
  murano:
    value: null
  murano_hash:
    value: null
  murano_roles:
    value: null
  murano_settings:
    value: null
  mysql:
    value: null
  mysql_hash:
    value: null
  network_config:
    value: null
  network_manager:
    value: null
  network_metadata:
    value: null
  network_scheme:
    value: null
  network_size:
    value: null
  neutron_advanced_configuration:
    value: null
  neutron_config:
    value: null
  neutron_db_password:
    value: null
  neutron_mellanox:
    value: null
  neutron_metadata_proxy_secret:
    value: null
  neutron_nodes:
    value: null
  neutron_user_password:
    value: null
  node:
    value: null
  node_name:
    value: null
  node_role:
    value: null
  nodes:
    value: null
  nodes_hash:
    value: null
  nova:
    value: null
  nova_api_nodes:
    value: null
  nova_db_password:
    value: null
  nova_hash:
    value: null
  nova_quota:
    value: null
  nova_rate_limits:
    value: null
  nova_report_interval:
    value: null
  nova_service_down_time:
    value: null
  novanetwork_params:
    value: null
  num_networks:
    value: null
  online:
    value: null
  openstack_version:
    value: null
  openstack_version_prev:
    value: null
  primary_controller:
    value: null
  priority:
    value: null
  private_int:
    value: null
  provision:
    value: null
  public_network_assignment:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  public_vrouter_vip:
    value: null
  puppet:
    value: null
  puppet_debug:
    value: null
  puppet_modules:
    value: null
  quantum:
    value: null
  quantum_settings:
    value: null
  queue_provider:
    value: null
  rabbit:
    value: null
  rabbit_ha_queues:
    value: null
  rabbit_hash:
    value: null
  repo_setup:
    value: null
  resume_guests_state_on_host_boot:
    value: null
  role:
    value: null
  roles:
    value: null
  sahara:
    value: null
  sahara_hash:
    value: null
  sahara_roles:
    value: null
  service_endpoint:
    value: null
  sql_connection:
    value: null
  status:
    value: null
  storage:
    value: null
  storage_hash:
    value: null
  storage_network_range:
    value: null
  swift:
    value: null
  swift_hash:
    value: null
  swift_master_role:
    value: null
  swift_nodes:
    value: null
  swift_proxies:
    value: null
  swift_proxy_caches:
    value: null
  syslog:
    value: null
  syslog_hash:
    value: null
  syslog_log_facility_ceilometer:
    value: null
  syslog_log_facility_ceph:
    value: null
  syslog_log_facility_cinder:
    value: null
  syslog_log_facility_glance:
    value: null
  syslog_log_facility_heat:
    value: null
  syslog_log_facility_keystone:
    value: null
  syslog_log_facility_murano:
    value: null
  syslog_log_facility_neutron:
    value: null
  syslog_log_facility_nova:
    value: null
  syslog_log_facility_sahara:
    value: null
  test_vm_image:
    value: null
  use_ceilometer:
    value: null
  use_cinder:
    value: null
  use_cow_images:
    value: null
  use_monit:
    value: null
  use_neutron:
    value: null
  use_ovs:
    value: null
  use_syslog:
    value: null
  use_vcenter:
    value: null
  user_node_name:
    value: null
  vcenter_hash:
    value: null
  verbose:
    value: null
  vlan_start:
    value: null
  workloads_collector:
    value: null
