id: dns-server
handler: puppetv2
version: '8.0'
actions:
  run: run.pp
  update: run.pp
input:
  external_dns:
    value: null
  fqdn:
    value: null
  management_vrouter_vip:
    value: null
  master_ip:
    value: null
  primary_controller:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
