id: openstack-haproxy-nova
handler: puppetv2
version: '8.0'
inputs:
  fqdn:
    value: null
  management_vip:
    value: null
  nova:
    value: null
  nova_api_nodes:
    value: null
  nova_ipaddresses:
    value: null
  nova_names:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
