id: genkeys
handler: shell
version: 0.0.1
input:
    uid:
        schema: str!
        value:
    path:
        schema: str!
        value: /var/lib/fuel/keys/
    ssl:
        schema: []
        value:
            - mongo
    ssh:
        schema: []
        value:
            - neutron
            - nova
            - mysql
