id: firewall
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  fqdn:
    value: null
  ironic:
    value: null
  master_ip:
    value: null
  network_scheme:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
