id: database
handler: puppetv2
version: '8.0'
inputs:
  database_nodes:
    value: null
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  mysql:
    value: null
  mysql_custom_setup_class:
    value: null
  network_scheme:
    value: null
  nodes:
    value: null
  primary_controller:
    value: null
  primary_database:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  use_syslog:
    value: null
