id: ntp-check
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  external_ntp:
    value: null
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
