id: openstack-haproxy-cinder
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  cinder_hash:
    value: null
  cinder_ipaddresses:
    value: null
  cinder_names:
    value: null
  cinder_nodes:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  network_metadata:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
