id: nova-db
handler: puppetv2
version: '8.0'
inputs:
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  mysql:
    value: null
  mysql_custom_setup_class:
    value: null
  nova:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
