id: librarian
handler: ansible
version: 0.0.1
input:
    modules:
      schema: [str]
      value: []
    modules_dir:
      schema: str!
      value: /etc/puppet/modules
    forge:
      schema: str!
      value: https://forgeapi.puppetlabs.com
