id: openstack-haproxy-ceilometer
handler: puppetv2
version: '8.0'
inputs:
  ceilometer:
    value: null
  ceilometer_nodes:
    value: null
  fqdn:
    value: null
  public_ssl:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
