id: openstack-haproxy-ceilometer
handler: puppetv2
version: '8.0'
actions:
  run: actions/run.pp
  update: actions/run.pp
input:
  ceilometer:
    value: null
  ceilometer_nodes:
    value: null
  fqdn:
    value: null
  public_ssl:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
